/* Generated by re2c 3.1 on Tue Sep 24 14:59:28 2024 */
#line 1 "C:\\Users\\newadmin\\source\\repos\\compiler\\compiler\\lexer.re"
#include "lexer.h"
#include <iostream>

Token Lexer(const char*& source) {
start:
	const char* begin = source;

#line 11 "lexer.cpp"
	{
		char yych;
		yych = *source;
		switch (yych) {
		case 0x00: goto yy1;
		case '\t':
		case '\n':
		case '\r':
		case ' ': goto yy4;
		case '!': goto yy6;
		case '%': goto yy8;
		case '&': goto yy9;
		case '(': goto yy10;
		case ')': goto yy11;
		case '*': goto yy12;
		case '+': goto yy13;
		case ',': goto yy14;
		case '-': goto yy15;
		case '/': goto yy17;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy18;
		case ';': goto yy20;
		case '<': goto yy21;
		case '=': goto yy23;
		case '>': goto yy25;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'c':
		case 'd':
		case 'g':
		case 'h':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'p':
		case 'q':
		case 's':
		case 'u':
		case 'v':
		case 'x':
		case 'y':
		case 'z': goto yy27;
		case '[': goto yy30;
		case ']': goto yy31;
		case 'b': goto yy32;
		case 'e': goto yy33;
		case 'f': goto yy34;
		case 'i': goto yy35;
		case 'o': goto yy36;
		case 'r': goto yy37;
		case 't': goto yy38;
		case 'w': goto yy39;
		case '{': goto yy40;
		case '|': goto yy41;
		case '}': goto yy42;
		default: goto yy2;
		}
	yy1:
		++source;
#line 52 "C:\\Users\\newadmin\\source\\repos\\compiler\\compiler\\lexer.re"
		{ return Token(ENDOFFILE); }
#line 109 "lexer.cpp"
		yy2:
		++source;
	yy3:
#line 53 "C:\\Users\\newadmin\\source\\repos\\compiler\\compiler\\lexer.re"
		{
			std::cerr << "Discarding unexpected character '"
				<< *begin << "'" << std::endl;
		}
#line 116 "lexer.cpp"
		yy4:
		yych = *++source;
		switch (yych) {
		case '\t':
		case '\n':
		case '\r':
		case ' ': goto yy4;
		default: goto yy5;
		}
	yy5:
#line 51 "C:\\Users\\newadmin\\source\\repos\\compiler\\compiler\\lexer.re"
		{ goto start; }
#line 129 "lexer.cpp"
		yy6 :
			yych = *++source;
		switch (yych) {
		case '=': goto yy43;
		default: goto yy7;
		}
	yy7:
#line 41 "C:\\Users\\newadmin\\source\\repos\\compiler\\compiler\\lexer.re"
		{ return SYMBOLNOT; }
#line 139 "lexer.cpp"
		yy8 :
			++source;
#line 32 "C:\\Users\\newadmin\\source\\repos\\compiler\\compiler\\lexer.re"
		{ return SYMBOLMODULO; }
#line 144 "lexer.cpp"
		yy9:
		yych = *++source;
		switch (yych) {
		case '&': goto yy44;
		default: goto yy3;
		}
	yy10:
		++source;
#line 42 "C:\\Users\\newadmin\\source\\repos\\compiler\\compiler\\lexer.re"
		{ return SYMBOLLBRACKET; }
#line 155 "lexer.cpp"
		yy11:
		++source;
#line 43 "C:\\Users\\newadmin\\source\\repos\\compiler\\compiler\\lexer.re"
		{ return SYMBOLRBRACKET; }
#line 160 "lexer.cpp"
		yy12:
		++source;
#line 30 "C:\\Users\\newadmin\\source\\repos\\compiler\\compiler\\lexer.re"
		{ return SYMBOLASTERISK; }
#line 165 "lexer.cpp"
		yy13:
		++source;
#line 28 "C:\\Users\\newadmin\\source\\repos\\compiler\\compiler\\lexer.re"
		{ return SYMBOLPLUS; }
#line 170 "lexer.cpp"
		yy14:
		++source;
#line 48 "C:\\Users\\newadmin\\source\\repos\\compiler\\compiler\\lexer.re"
		{ return SYMBOLCOMMA; }
#line 175 "lexer.cpp"
		yy15:
		yych = *++source;
		switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy18;
		default: goto yy16;
		}
	yy16:
#line 29 "C:\\Users\\newadmin\\source\\repos\\compiler\\compiler\\lexer.re"
		{ return SYMBOLMINUS; }
#line 194 "lexer.cpp"
		yy17 :
			++source;
#line 31 "C:\\Users\\newadmin\\source\\repos\\compiler\\compiler\\lexer.re"
		{ return SYMBOLSLASH; }
#line 199 "lexer.cpp"
		yy18:
		yych = *++source;
		switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy18;
		default: goto yy19;
		}
	yy19:
#line 17 "C:\\Users\\newadmin\\source\\repos\\compiler\\compiler\\lexer.re"
		{ return Token(atoi(begin)); }
#line 218 "lexer.cpp"
		yy20 :
			++source;
#line 50 "C:\\Users\\newadmin\\source\\repos\\compiler\\compiler\\lexer.re"
		{ return SYMBOLSEMICOLON; }
#line 223 "lexer.cpp"
		yy21:
		yych = *++source;
		switch (yych) {
		case '=': goto yy45;
		default: goto yy22;
		}
	yy22:
#line 35 "C:\\Users\\newadmin\\source\\repos\\compiler\\compiler\\lexer.re"
		{ return SYMBOLLESSTHAN; }
#line 233 "lexer.cpp"
		yy23 :
			yych = *++source;
		switch (yych) {
		case '=': goto yy46;
		default: goto yy24;
		}
	yy24:
#line 49 "C:\\Users\\newadmin\\source\\repos\\compiler\\compiler\\lexer.re"
		{ return ASSIGN; }
#line 243 "lexer.cpp"
		yy25 :
			yych = *++source;
		switch (yych) {
		case '=': goto yy47;
		default: goto yy26;
		}
	yy26:
#line 37 "C:\\Users\\newadmin\\source\\repos\\compiler\\compiler\\lexer.re"
		{ return SYMBOLGREATERTHAN; }
#line 253 "lexer.cpp"
		yy27 :
			yych = *++source;
	yy28:
		switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy27;
		default: goto yy29;
		}
	yy29:
#line 27 "C:\\Users\\newadmin\\source\\repos\\compiler\\compiler\\lexer.re"
		{ return Token(std::string(begin, source)); }
#line 326 "lexer.cpp"
		yy30 :
			++source;
#line 46 "C:\\Users\\newadmin\\source\\repos\\compiler\\compiler\\lexer.re"
		{ return SYMBOLLSQUAREBRACKET; }
#line 331 "lexer.cpp"
		yy31:
		++source;
#line 47 "C:\\Users\\newadmin\\source\\repos\\compiler\\compiler\\lexer.re"
		{ return SYMBOLRSQUAREBRACKET; }
#line 336 "lexer.cpp"
		yy32:
		yych = *++source;
		switch (yych) {
		case 'o': goto yy48;
		default: goto yy28;
		}
	yy33:
		yych = *++source;
		switch (yych) {
		case 'l': goto yy49;
		default: goto yy28;
		}
	yy34:
		yych = *++source;
		switch (yych) {
		case 'a': goto yy50;
		default: goto yy28;
		}
	yy35:
		yych = *++source;
		switch (yych) {
		case 'f': goto yy51;
		case 'n': goto yy53;
		default: goto yy28;
		}
	yy36:
		yych = *++source;
		switch (yych) {
		case 'p': goto yy54;
		default: goto yy28;
		}
	yy37:
		yych = *++source;
		switch (yych) {
		case 'e': goto yy55;
		default: goto yy28;
		}
	yy38:
		yych = *++source;
		switch (yych) {
		case 'r': goto yy56;
		default: goto yy28;
		}
	yy39:
		yych = *++source;
		switch (yych) {
		case 'h': goto yy57;
		default: goto yy28;
		}
	yy40:
		++source;
#line 44 "C:\\Users\\newadmin\\source\\repos\\compiler\\compiler\\lexer.re"
		{ return SYMBOLLBRACE; }
#line 390 "lexer.cpp"
		yy41:
		yych = *++source;
		switch (yych) {
		case '|': goto yy58;
		default: goto yy3;
		}
	yy42:
		++source;
#line 45 "C:\\Users\\newadmin\\source\\repos\\compiler\\compiler\\lexer.re"
		{ return SYMBOLRBRACE; }
#line 401 "lexer.cpp"
		yy43:
		++source;
#line 34 "C:\\Users\\newadmin\\source\\repos\\compiler\\compiler\\lexer.re"
		{ return SYMBOLNOTEQUAL; }
#line 406 "lexer.cpp"
		yy44:
		++source;
#line 39 "C:\\Users\\newadmin\\source\\repos\\compiler\\compiler\\lexer.re"
		{ return SYMBOLAND; }
#line 411 "lexer.cpp"
		yy45:
		++source;
#line 36 "C:\\Users\\newadmin\\source\\repos\\compiler\\compiler\\lexer.re"
		{ return SYMBOLLESSTHANEQUAL; }
#line 416 "lexer.cpp"
		yy46:
		++source;
#line 33 "C:\\Users\\newadmin\\source\\repos\\compiler\\compiler\\lexer.re"
		{ return SYMBOLEQUAL; }
#line 421 "lexer.cpp"
		yy47:
		++source;
#line 38 "C:\\Users\\newadmin\\source\\repos\\compiler\\compiler\\lexer.re"
		{ return SYMBOLGREATERTHANEQUAL; }
#line 426 "lexer.cpp"
		yy48:
		yych = *++source;
		switch (yych) {
		case 'o': goto yy59;
		default: goto yy28;
		}
	yy49:
		yych = *++source;
		switch (yych) {
		case 's': goto yy60;
		default: goto yy28;
		}
	yy50:
		yych = *++source;
		switch (yych) {
		case 'l': goto yy61;
		default: goto yy28;
		}
	yy51:
		yych = *++source;
		switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy27;
		default: goto yy52;
		}
	yy52:
#line 22 "C:\\Users\\newadmin\\source\\repos\\compiler\\compiler\\lexer.re"
		{ return IF; }
#line 516 "lexer.cpp"
		yy53 :
			yych = *++source;
		switch (yych) {
		case 't': goto yy62;
		default: goto yy28;
		}
	yy54:
		yych = *++source;
		switch (yych) {
		case 'e': goto yy64;
		default: goto yy28;
		}
	yy55:
		yych = *++source;
		switch (yych) {
		case 't': goto yy65;
		default: goto yy28;
		}
	yy56:
		yych = *++source;
		switch (yych) {
		case 'u': goto yy66;
		default: goto yy28;
		}
	yy57:
		yych = *++source;
		switch (yych) {
		case 'i': goto yy67;
		default: goto yy28;
		}
	yy58:
		++source;
#line 40 "C:\\Users\\newadmin\\source\\repos\\compiler\\compiler\\lexer.re"
		{ return SYMBOLOR; }
#line 551 "lexer.cpp"
		yy59:
		yych = *++source;
		switch (yych) {
		case 'l': goto yy68;
		default: goto yy28;
		}
	yy60:
		yych = *++source;
		switch (yych) {
		case 'e': goto yy70;
		default: goto yy28;
		}
	yy61:
		yych = *++source;
		switch (yych) {
		case 's': goto yy72;
		default: goto yy28;
		}
	yy62:
		yych = *++source;
		switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy27;
		default: goto yy63;
		}
	yy63:
#line 21 "C:\\Users\\newadmin\\source\\repos\\compiler\\compiler\\lexer.re"
		{ return INT; }
#line 641 "lexer.cpp"
		yy64 :
			yych = *++source;
		switch (yych) {
		case 'r': goto yy73;
		default: goto yy28;
		}
	yy65:
		yych = *++source;
		switch (yych) {
		case 'u': goto yy74;
		default: goto yy28;
		}
	yy66:
		yych = *++source;
		switch (yych) {
		case 'e': goto yy75;
		default: goto yy28;
		}
	yy67:
		yych = *++source;
		switch (yych) {
		case 'l': goto yy77;
		default: goto yy28;
		}
	yy68:
		yych = *++source;
		switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy27;
		default: goto yy69;
		}
	yy69:
#line 18 "C:\\Users\\newadmin\\source\\repos\\compiler\\compiler\\lexer.re"
		{ return BOOL; }
#line 737 "lexer.cpp"
		yy70 :
			yych = *++source;
		switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy27;
		default: goto yy71;
		}
	yy71:
#line 23 "C:\\Users\\newadmin\\source\\repos\\compiler\\compiler\\lexer.re"
		{ return ELSE; }
#line 809 "lexer.cpp"
		yy72 :
			yych = *++source;
		switch (yych) {
		case 'e': goto yy78;
		default: goto yy28;
		}
	yy73:
		yych = *++source;
		switch (yych) {
		case 'a': goto yy80;
		default: goto yy28;
		}
	yy74:
		yych = *++source;
		switch (yych) {
		case 'r': goto yy81;
		default: goto yy28;
		}
	yy75:
		yych = *++source;
		switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy27;
		default: goto yy76;
		}
	yy76:
#line 19 "C:\\Users\\newadmin\\source\\repos\\compiler\\compiler\\lexer.re"
		{ return TRUE; }
#line 899 "lexer.cpp"
		yy77 :
			yych = *++source;
		switch (yych) {
		case 'e': goto yy82;
		default: goto yy28;
		}
	yy78:
		yych = *++source;
		switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy27;
		default: goto yy79;
		}
	yy79:
#line 20 "C:\\Users\\newadmin\\source\\repos\\compiler\\compiler\\lexer.re"
		{ return FALSE; }
#line 977 "lexer.cpp"
		yy80 :
			yych = *++source;
		switch (yych) {
		case 't': goto yy84;
		default: goto yy28;
		}
	yy81:
		yych = *++source;
		switch (yych) {
		case 'n': goto yy85;
		default: goto yy28;
		}
	yy82:
		yych = *++source;
		switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy27;
		default: goto yy83;
		}
	yy83:
#line 26 "C:\\Users\\newadmin\\source\\repos\\compiler\\compiler\\lexer.re"
		{ return WHILE; }
#line 1061 "lexer.cpp"
		yy84 :
			yych = *++source;
		switch (yych) {
		case 'o': goto yy87;
		default: goto yy28;
		}
	yy85:
		yych = *++source;
		switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy27;
		default: goto yy86;
		}
	yy86:
#line 25 "C:\\Users\\newadmin\\source\\repos\\compiler\\compiler\\lexer.re"
		{ return RETURN; }
#line 1139 "lexer.cpp"
		yy87 :
			yych = *++source;
		switch (yych) {
		case 'r': goto yy88;
		default: goto yy28;
		}
	yy88:
		yych = *++source;
		switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy27;
		default: goto yy89;
		}
	yy89:
#line 24 "C:\\Users\\newadmin\\source\\repos\\compiler\\compiler\\lexer.re"
		{ return OPERATOR; }
#line 1217 "lexer.cpp"
	}
#line 55 "C:\\Users\\newadmin\\source\\repos\\compiler\\compiler\\lexer.re"

}